apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:8080
        isDefault: true
        editable: true
        orgId: 1
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-headless:3100
        jsonData:
          maxLines: 1000