# docker-compose -f monitoring-compose.yml up
version: "3.9"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes: 
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports: 
      - "3000:3000"
    volumes: 
      - "./config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
  loki:
    image: grafana/loki:2.3.0
    hostname: "loki"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes: 
      - "./config/loki-config.yml:/etc/loki/local-config.yaml"
networks:
  default:
    name: neo4jnetwork
