apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config-server1
  namespace: neo4j
data:
  promtail.yaml: |-
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-headless.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: neo4j_query_log_1
        static_configs:
        - targets:
            - loki
          labels:
            job: querylogs1
            type: querylog
            __path__: /log/query.log

    