apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: 'neo4j-prometheus'
        scrape_interval: 10s
        static_configs:
        - targets: ['server1-admin.neo4j.svc.cluster.local:2004']
          labels:
            instance: 'core1'
        - targets: ['server2-admin.neo4j.svc.cluster.local:2004']
          labels:
            instance: 'core2'
        - targets: ['server3-admin.neo4j.svc.cluster.local:2004']
          labels:
            instance: 'core3'
        - targets: ['server4-admin.neo4j.svc.cluster.local:2004']
          labels:
            instance: 'core4'
