apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: 'neo4j-prometheus'
        scrape_interval: 10s
        static_configs:
        - targets: [
          'server1-admin.neo4j.svc.cluster.local:2004',
          'server2-admin.neo4j.svc.cluster.local:2004',
          'server3-admin.neo4j.svc.cluster.local:2004',
          'server4-admin.neo4j.svc.cluster.local:2004'
        ]
          labels:
            instance: 'core1'
