{
 "title": "Neo4j 4.0 Overall Cluster Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": "prometheus" },
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "neo4j_instance", "label": "Neo4j Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Database", "query": { "query": "metrics(_store_size)" } },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "leader",
    "label": "Leader",
    "query": {
     "query": "query_result(neo4j_database_[[Database]]_cluster_core_is_leader > 0 )"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Neo4j Status  - core1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"core1\"}"
    }
   ]
  },
  {
   "title": "Neo4j Status  - core2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"core2\"}"
    }
   ]
  },
  {
   "title": "Neo4j Status  - core3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"core3\"}"
    }
   ]
  },
  {
   "title": "Neo4j Status  - core4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"core4\"}"
    }
   ]
  },
  {
   "title": "Neo4j Status  - core5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"core5\"}"
    }
   ]
  },
  {
   "title": "Instance \"core1\" Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"core1\"}"
    }
   ]
  },
  {
   "title": "Instance \"core2\" Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"core2\"}"
    }
   ]
  },
  {
   "title": "Instance \"core3\" Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"core3\"} "
    }
   ]
  },
  {
   "title": "Instance \"core4\" Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"core3\"} "
    }
   ]
  },
  {
   "title": "Instance \"core5\" Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"core5\"} "
    }
   ]
  },
  {
   "title": "Total Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_neo4j_count_node{instance=~\"$leader\", job=\"neo4j-prometheus\"}"
    }
   ]
  },
  {
   "title": "Total Number of Relationships",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_neo4j_count_relationship{instance=~\"$leader\"}"
    }
   ]
  },
  {
   "title": "Total. Store Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_store_size_total{instance=~\"$leader\"}"
    }
   ]
  },
  {
   "title": "Current Leader",
   "type": "graph",
   "gridPos": { "h": 14, "w": 4, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_cluster_core_is_leader{instance=~\"$neo4j_instance\"}"
    }
   ]
  },
  {
   "title": "Graph Items Creation Rate (ids)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_database_[[Database]]_ids_in_use_node{instance=~\"$neo4j_instance\"}[$interval])"
    },
    {
     "expr": "rate(neo4j_database_[[Database]]_ids_in_use_relationship{instance=~\"$neo4j_instance\"}[$interval])"
    },
    {
     "expr": "rate(neo4j_database_[[Database]]_ids_in_use_property{instance=~\"$neo4j_instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Database Size on Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_store_size_total{instance=~\"$neo4j_instance\"}"
    }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(neo4j_database_[[Database]]_transaction_committed_total[$interval])"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "graph",
   "description": "Active Transactions - Read and Write - \nand Peak concurrent",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_read{instance=~\"$neo4j_instance\"}"
    },
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"$neo4j_instance\"}"
    },
    {
     "expr": "neo4j_database_[[Database]]_transaction_peak_concurrent_total{instance=~\"$neo4j_instance\"}"
    }
   ]
  },
  {
   "title": "Counters of Graph Items",
   "type": "graph",
   "description": "Total number of graph items: node, relationships, ...",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_database_[[Database]]_ids_in_use_(node|property|relationship)\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_database_[[Database]]_ids_in_use_(.+)\")"
    },
    {
     "expr": "neo4j_database_[[Database]]_ids_in_use_relationship_type{instance=~\"$neo4j_instance\"}  "
    }
   ]
  },
  {
   "title": "Checkpoint Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idelta(neo4j_database_[[Database]]_check_point_total_time_total{instance=~\"$neo4j_instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Bolt Connections Running",
   "type": "graph",
   "description": "The total number of Bolt connections currently being executed.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " neo4j_dbms_bolt_connections_running{instance=~\"$neo4j_instance\"} "
    }
   ]
  },
  {
   "title": "Committed transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_committed_total{instance=~\"$neo4j_instance\"}  "
    },
    {
     "expr": "neo4j_database_[[Database]]_transaction_committed_read_total{instance=~\"$neo4j_instance\"}  "
    },
    {
     "expr": "neo4j_database_[[Database]]_transaction_committed_write_total{instance=~\"$neo4j_instance\"}  "
    }
   ]
  },
  {
   "title": "Last Committed Transaction ID",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_last_committed_tx_id_total{instance=~\"$neo4j_instance\"}"
    }
   ]
  },
  {
   "title": "Page Cache Total Faults",
   "type": "graph",
   "description": "The total number of page faults happened in the page cache\n\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(neo4j_dbms_page_cache_page_faults_total{instance=~\"$neo4j_instance\"}[$interval]) "
    }
   ]
  },
  {
   "title": "Cypher Replan Events",
   "type": "graph",
   "description": "Neo4j caches 1000 plans by default. Seeing sustained replanning events or large spikes could indicate an issue that needs to be investigated.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_cypher_replan_events_total{instance=~\"$neo4j_instance\"}"
    }
   ]
  },
  {
   "title": "Page Cache Usage Ratio",
   "type": "graph",
   "description": "This metric shows what percentage of the allocated page cache is actually being used. If it is 100%, then it is likely that the hitratio will start dropping, and you should consider allocating more RAM to page cache.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_dbms_page_cache_usage_ratio{instance=~\"$neo4j_instance\"}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "neo4j_dbms_vm_heap_used{instance=~\"$neo4j_instance\"}"
    }
   ]
  },
  {
   "title": "Pagecache Hit Ratio",
   "type": "graph",
   "description": "Performance relies on efficiently using the page cache, so this metric should be in the 98-100% range consistently. If it is much lower than that, then the database is going to disk too often.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_dbms_page_cache_hit_ratio{instance=~\"$neo4j_instance\"}"
    }
   ]
  },
  {
   "title": "Garbage Collection Pause Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idelta(neo4j_dbms_vm_gc_time_g1_old_generation_total[$interval])+idelta(neo4j_dbms_vm_gc_time_g1_young_generation_total[$interval])"
    }
   ]
  }
 ]
}