scrape_configs:
  - job_name: 'neo4j-prometheus'
    scrape_interval: 10s
    static_configs:
    - targets: ['20.223.32.151:2004']
      labels:
        instance: 'core1'
    - targets: ['20.223.121.130:2004']
      labels:
        instance: 'core2'
    - targets: ['20.223.121.149:2004']
      labels:
        instance: 'core3'
    - targets: ['20.223.121.150:2004']
      labels:
        instance: 'core4'
    - targets: ['20.223.121.162:2004']
      labels:
        instance: 'core5'