scrape_configs:
  - job_name: 'neo4j-prometheus'
    scrape_interval: 10s
    static_configs:
    - targets: ['neo4j-server-1:2004']
      labels:
        instance: 'core1'
    - targets: ['neo4j-server-2:2004']
      labels:
        instance: 'core2'
    - targets: ['neo4j-server-3:2004']
      labels:
        instance: 'core3'
    - targets: ['neo4j-server-4:2004']
      labels:
        instance: 'core4'
    - targets: ['neo4j-server-5:2004']
      labels:
        instance: 'core5'