scrape_configs:
  - job_name: 'neo4j-prometheus'
    scrape_interval: 10s
    static_configs:
    - targets: ['51.138.232.213:2004']
      labels:
        instance: 'core1'
    - targets: ['51.138.232.216:2004']
      labels:
        instance: 'core2'
    - targets: ['51.138.232.218:2004']
      labels:
        instance: 'core3'