{
 "title": "Neo4j 5 Query log dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "prometheus" },
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "neo4j_instance", "label": "Neo4j Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Database", "query": { "query": "metrics(_store_size)" } },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "leader",
    "label": "Leader",
    "query": {
     "query": "query_result(neo4j_database_[[Database]]_cluster_core_is_leader > 0 )"
    }
   },
   { "name": "search_log", "label": "search_log" }
  ]
 },
 "panels": [
  {
   "title": "Security log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{type=\"securitylog\"} | json "
    }
   ]
  },
  { "title": "Query log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Query response time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by(query) (avg_over_time({type=\"querylog\"} |= `elapsedTimeMs` | json | line_format `{{. elapsedTimeMs}}` | database = `$Database` | unwrap elapsedTimeMs [1m]))"
    }
   ]
  },
  {
   "title": "Query planner time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg by(query) (avg_over_time({type=\"querylog\"} |= `elapsedTimeMs` | json | line_format `{{. elapsedTimeMs}}` | database = `$Database` | unwrap planning [1m]))"
    }
   ]
  },
  {
   "title": "Total query time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(query) (avg_over_time({type=\"querylog\"} |= `elapsedTimeMs` | json | line_format `{{. elapsedTimeMs}}` | database = `$Database` | unwrap elapsedTimeMs [1m]))"
    }
   ]
  },
  {
   "title": "Average load by server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "avg by(job) (avg_over_time({type=\"querylog\"} |= `elapsedTimeMs` | json | line_format `{{. elapsedTimeMs}}` | database = `$Database` | unwrap elapsedTimeMs [1m]))"
    }
   ]
  },
  {
   "title": "Total query time by client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum by( annotationData ) (avg_over_time({type=\"querylog\"} |= `elapsedTimeMs` | json | line_format `{{. elapsedTimeMs}}` | database = `$Database` | unwrap elapsedTimeMs [1m]))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{type=\"querylog\"} | json | database = `$Database` |~ `$search_log`"
    }
   ]
  },
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Neo4j Status  - core1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"core1\"}"
    }
   ]
  },
  {
   "title": "Neo4j Status  - core2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"core2\"}"
    }
   ]
  },
  {
   "title": "Neo4j Status  - core3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"core3\"}"
    }
   ]
  },
  {
   "title": "Neo4j Status  - core4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"core4\"}"
    }
   ]
  },
  {
   "title": "Neo4j Status  - core5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "neo4j_database_[[Database]]_transaction_active_write{instance=~\"core5\"}"
    }
   ]
  },
  {
   "title": "Server \"core1\" Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"core1\"}"
    }
   ]
  },
  {
   "title": "Server \"core2\" Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"core2\"}"
    }
   ]
  },
  {
   "title": "Server \"core3\" Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"core3\"} "
    }
   ]
  },
  {
   "title": "Server \"core4\" Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"core3\"} "
    }
   ]
  },
  {
   "title": "Server \"core5\" Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"core5\"} "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "targets": [
    { "cypherQuery": "call dbms.listConfig()" }
   ]
  }
 ]
}